export default [
  {
    author: 'Олександр Омельченко',
    url: 'https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/',
    name: 'Статус посилки',
    date: '10.10.2020',
    time: '14:00',
    id: 1,
  },
  {
    author: 'Павло Кринчук',
    url: 'https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/',
    name: 'Статус посилки',
    date: '10.10.2020',
    time: '14:00',
    id: 2,
  },
  {
    author: 'Олена Нагоренко',
    url: 'https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/',
    name: 'Список вільних столиків',
    date: '10.10.2020',
    time: '14:00',
    id: 3,
  },
  {
    author: 'Алла Гриценко',
    url: 'https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/',
    name: 'Статус посилки',
    date: '10.10.2020',
    time: '14:00',
    id: 4,
  },
  {
    author: 'Дмитро Назарчук',
    url: 'https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/',
    name: 'Список вільних столиків',
    date: '10.10.2020',
    time: '14:00',
    id: 5,
  },
  {
    author: 'Денис Шевченко',
    url: 'https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/',
    name: 'Статус посилки',
    date: '10.10.2020',
    time: '14:00',
    id: 6,
  },
  {
    author: 'Олександр Омельченко',
    url: 'https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/',
    name: 'Апдейт угоди',
    date: '10.10.2020',
    time: '14:00',
    id: 7,
  },
  {
    author: 'Дмитро Назарчук',
    url: 'https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/',
    name: 'Апдейт угоди',
    date: '10.10.2020',
    time: '14:00',
    id: 8,
  },
  {
    author: 'Денис Шевченко',
    url: 'https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/',
    name: 'Статус посилки',
    date: '10.10.2020',
    time: '14:00',
    id: 9,
  },
  {
    author: 'Олена Нагоренко',
    url: 'https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/',
    name: 'Список вільних столиків',
    date: '10.10.2020',
    time: '14:00',
    id: 10,
  },
  {
    author: 'Алла Гриценко',
    url: 'https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/',
    name: 'Статус посилки',
    date: '10.10.2020',
    time: '14:00',
    id: 11,
  },
  {
    author: 'Алла Гриценко',
    url: 'https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/',
    name: 'Список вільних столиків',
    date: '10.10.2020',
    time: '14:00',
    id: 12,
  },
  {
    author: 'Олександр Омельченко',
    url: 'https://yesoriginal.inboost.ai/api/webhok/retwsdhgds32/',
    name: 'Апдейт угоди',
    date: '10.10.2020',
    time: '14:00',
    id: 13,
  },
];
